### ISSUE TITLE
All absences this week

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/agile-team-dashboard#14]
We want to show in the main page (`dashboard#index`) view all the people absences in the next 7 days. At the moment we only show the absences of the current day.

* Create a scope to get the absences of the next 7 days.

**Comment by Ana06** [comment]
@DavidKang I know you didn't add the issue, but please document this properly if you want to make it a junior issue. Al least a description (because I doubt that anybody outside the team would understand this without a proper explanation) and a list of tasks if apply. In general the issue should be good explained, but if we label it as junior I would say we should make an extra effort to ensure that it is clear. The difficult part should be coding not understanding what to do. :wink: 

@mschnitzer you shouldn't open issues without a description, all the issues you add in this repo doesn't have any explanation, just a short title. Could you please review the ones that are still open?

**Comment by Ana06** [comment]
Thanks @DavidKang

**Comment by rishabhptr** [comment]
Is there already someone working on this? Can I give it a go?

**Comment by DavidKang** [comment]
@rishabhptr, is all yours, go ahead 👍
