### ISSUE TITLE
Add pagination for meeting, absence and sprint

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/agile-team-dashboard#67]
We need to add a pagination for the finished items list in the index view of each of them. We could use [Kaminari gem](https://github.com/kaminari/kaminari) or other.

**Comment by Ana06** [comment]
So for example for Meetings:

![image](https://user-images.githubusercontent.com/16052290/30858674-edcfc3fa-a2c0-11e7-9038-177adb68e530.png)

In Finished meeting we are showing all of them. If there are 2000 finished meetings this page will get really long. Because of that, we need pagination, so only some of them are seen at the same time.

And the same for Absence and Sprint. :smile: 

And I think that could be a junior issue too. :wink:

**Comment by rahul2240** [comment]
can i take this?

**Comment by DavidKang** [comment]
@rahul2240, I'm working on it, sorry

**Comment by rahul2240** [comment]
@DavidKang Ok no problem :smile:  i will remove my branch

**Comment by Ana06** [comment]
@DavidKang if we introduce [SmartListing](https://github.com/Sology/smart_listing), we can use this gem for this as well. See https://github.com/openSUSE/agile-team-dashboard/pull/94

**Comment by AnkushMalik** [comment]
can i take this or @DavidKang are u working on this?

**Comment by Ana06** [comment]
you can work on it @AnkushMalik 😉

**Comment by DavidKang** [comment]
@AnkushMalik, sure 😸
