### ISSUE TITLE
Add missing event type in meeting

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/agile-team-dashboard#68]
'Grooming' meeting is missed in the event type of meeting

**Comment by Ana06** [comment]
And what is the current type of grooming?

**Comment by DavidKang** [comment]
@Ana, in the meeting model we have a `types` constant where a type is missed, in this case `grooming`

**Comment by Ana06** [comment]
@DavidKang yes, but what type is beeing used when creating a Grooming meeting at the moment? Because meetings are automatically created when creating a Sprint.

**Comment by Ana06** [comment]
@DavidKang yes, but what type is beeing used when creating a Grooming meeting at the moment? Because meetings are automatically created when creating a Sprint. 

Ok.. it seems we are assigning this and we don't have a validation. So, thinks needed to fix this:

- Add `Grooming` type to event type list in Meeting model
- Add validation to ensure that only the valid types are used.

And this can be a junior issue :wink:

**Comment by rahul2240** [comment]
can i do this?

**Comment by DavidKang** [comment]
@rahul2240, sure!
